version: '3'

tasks:
  renovate:
    cmds:
      - |
        echo "Running Renovate..."
        npx renovate@latest . \
          --platform=local \
          --autodiscover=false \
          --config renovate.json \
          > renovate.log 2>&1
    silent: false

  show-log:
    cmds:
      - cat renovate.log
    silent: false